sudo: false
language: python
python:
    - 2.7
    - 3.5
env:
  matrix:
    - DJANGO='django>=1.7,<1.8'
    - DJANGO='django>=1.8,<1.9'
    - DJANGO='--upgrade --pre django'
install:
   - pip install $DJANGO
script:
    - make test
